### ISSUE TITLE
Procedural API: no Cyan color?

### ISSUE THREAD

**Issue by kelvinhsung** [GameThemedGroup/Corrupted#1]

**Comment by TaranChristensen** [comment]
It looks like "Light Blue" resolved to "Cyan". I suspect this was for easy of use for kids, who might not know what the color Cyan is, but understand Light Blue. I've added an extra word definition for Cyan, so a student can use either "Cyan" or "Light Blue" to refer to the color. This will not affect the frequency of a Cyan block spawning from the shooter. Also, it looks like if a student misspells any color, it will default to Cyan, so typing in "Cyan" previously would have functioned the same. I've kept the changes in anyways, for clarity for the next person who looks at the code.
