### ISSUE TITLE
Teaching Material writeup ...

### ISSUE THREAD

**Issue by kelvinhsung** [GameThemedGroup/Corrupted#2]
Lab3:

buildWorld() <-- this should be buildGame()

**Comment by TaranChristensen** [comment]
Changed the method to buildGame() as mentioned.

I also changed updateWorld() to updateGame(). The updateWorld() function appears to have worked fine, but every other lab uses updateGame(), which also works.

I doubled checked the other labs and did not find this typo elsewhere.

**Comment by kelvinhsung** [comment]
Excellent! Thank you
